model-car:
- name: nvidia-nemotron-3-nano-30b-a3b-fp8
  image: registry.stage.redhat.io/rhai/modelcar-nvidia-nemotron-3-nano-30b-a3b-fp8:3.0
  model_output_type: text
  serving_arguments:
    args:
    - --uvicorn-log-level=info
    - --trust-remote-code
    - --tensor-parallel-size=1
    - --max-model-len=2048
    gpu_count: 1
- name: apertus-8b-instruct-2509-fp8-dynamic
  image: registry.stage.redhat.io/rhai/modelcar-apertus-8b-instruct-2509-fp8-dynamic:3.0
  model_output_type: text
  serving_arguments:
    args:
    - --uvicorn-log-level=info
    - --trust-remote-code
    - --tensor-parallel-size=1
    - --max-model-len=2048
    gpu_count: 1
